### ISSUE TITLE
Set up Linode

### ISSUE THREAD

**Issue by michhub-dev** [michhub-dev/AfricaHacks2020-Handiwork#11]

**Comment by devolusegun** [comment]
Host site: linode https://login.linode.com/signup?promo=hack20

**Comment by devolusegun** [comment]
https://cloud.linode.com/dashboard

USERNAME: handiwork

**Comment by devolusegun** [comment]
**Completed, linode setup.** 
* Linode nameservers linked with our domain [www.handiwork.xyz](http://handywork.xyz) on Namecheap.com
